name: CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          v install --git https://github.com/jdonnerstag/vlang-yaml
          v install

      - name: Check if code is formatted
        run: |
          v fmt -diff .
          v fmt -verify .

      - name: Build ${{ github.event.repository.name }}
        run: v .

      - name: Run Tests
        run: v test .
  
  docker:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@master
      
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: openapi2cli
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
